### ISSUE TITLE
tab-completion for interactivity?

### ISSUE THREAD

**Issue by amueller** [bokeh/colorcet#1]
This is a usability question. It looks to me like all the colormaps are available via the ``cc.cm`` dictionary. However, there is no auto-complete for dictionaries in jupyter notebook, so I either need to remember the name exactly and type it out, or call ``cm.keys()``, search for the colormap, and copy and paste the string.

Maybe there's an easier way that I don't see?

If I could use jupyters auto-complete to find the right color map, that would be much easier given your naming schemes. One way to achieve that would be to make ``cm`` be a bunch object, so that the items can be obtained with ``__get_attr__``. If you define ``__dir__`` right, that allows tab-completion.
You could also define a sub-module that has instances of the colormaps with appropriate names (I think that's what matplotlib does?)

Thanks for these great colormaps!

**Comment by jbednar** [comment]
Sorry; I didn't get a notice of this question when it came in!  I tried to make all the colormaps available in several different ways to make them convenient to use in different contexts. If you import colorcet, all the colormaps should autocomplete already in the colorcet namespace:

![image](https://cloud.githubusercontent.com/assets/1695496/21161377/eae4de50-c14d-11e6-984b-e994bc11514f.png)

(Here the "m_" prefix gives you the matplotlib colormaps, while "b_" will give Bokeh palettes.)  But I'd be happy to accept a pull request to define ``__get_attr__`` and ``__dir__`` to work for ``cc.cm``, if that helps anyone!

**Comment by jbednar** [comment]
(And if someone happens to get that in today :-), it would make it in time for the new release scheduled for tomorrow; otherwise it will be in the subsequent one.)

**Comment by amueller** [comment]
ah, cool. is that documented? That totally solves my issue. I just didn't find it.

**Comment by jbednar** [comment]
Good point; it was not well documented, but hopefully it is now: https://bokeh.github.io/colorcet/#Accessing-the-colormaps

**Comment by amueller** [comment]
thanks!
