### ISSUE TITLE
ECCN number for colorcet

### ISSUE THREAD

**Issue by kbhatna1** [bokeh/colorcet#10]
hi Team,
could you p[lease help us with the ECCN number of the software colorcet version. 
If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess:

  | NO | YES
-- | -- | --
Does the Software perform any encryption or utilize any   encryption processes? |   |  
If the answer is YES to the above, please indicate if the   encryption is coded into the application or separately called (such as using   SSL) |   |  
If the answer is YES to the above, please indicate what   function(s) the cryptography/encryption serves |   |  
A,  Copyright protection purposes (Includes using a license   key/code) |   |  
B, User authentication purposes |   |  
C, A core part of the functionality such as to encrypt   databases       D, To encrypt communications between the software and a host   system |   |  
D, To encrypt communications between the software and a host system?

Regards,
Kriti Bhatnagar
Software analyst
New Products & Complex Team
EMIT | IT OPS | CES | WDS | SAM 
 
HCL Technologies Limited
(CIN: L74140DL1991PLC046369)
10th Floor, ODC-IV, Software Tower 6, Sector 126
Noida SEZ, Uttar Pradesh – 201301, India
Phone: +1-4088093746 (ext.4144395)
Email:- kriti.bhatnagar@exxonmobil.com
for
 
ExxonMobil Global Services Company
22777 Springwoods Village Parkway
Spring, TX 77389
United States of America

**Comment by jbednar** [comment]
The answer is No or N/A to all of the above; colorcet does not require or use any encryption technologies.
