### ISSUE TITLE
license of color scales

### ISSUE THREAD

**Issue by mkborregaard** [bokeh/colorcet#3]
Hi, I think these color scales are great and would love to have them available to the Julia community. What license are they released under? I would like to copy the scales to the Julia package PlotUtils, which is under the MIT license. A reference to this repo would appear in the source file and in the documentation (at juliaplots.github.io).
Thanks!

**Comment by bryevdv** [comment]
I'm sure @jbednar can comment about the colorcet license. As a completely tangential aside, I'd just like to say that I think Bokeh itself would be great to make available to the Julia community. If you or anyone you know might be interested in picking up the old Bokeh.jl work, and updating it to current versions of Bokeh, please reach out to us.

**Comment by jbednar** [comment]
The [license](https://github.com/bokeh/colorcet/blob/master/LICENSE.txt) is CC-BY, and they are already available for [Julia](https://github.com/peterkovesi/PerceptualColourMaps.jl), so please use them all you like!  The only exception may be the "fire" colormap, which Peter Kovesi added at my request when I was making the Python version, and I'm not sure if he's updated the versions for other languages to include it.  If he hasn't, I'm sure he'd be happy with a pull request on his PR to make that small update, using the values from the Python version...

**Comment by mkborregaard** [comment]
Thanks a lot!
Oh and @bryevdv yes it'd be great to revive Bokeh.jl. Julia currently suffers from having more enthusiasm and ambition than people who engage to build and maintain packages, but I am sure this will improve in the future.
